#=================================================
# https://github.com/miaoxinwei/openwrt_build
# Description: Build OpenWrt using GitHub Actions
# Lisence: AGPL-3.0
# Author: MXW
#=================================================

name: 16m 固件

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@main
        
      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get clean
          
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo timedatectl set-timezone "$TZ"

      - name: 克隆代码
        env:
          REPO_URL: https://github.com/openwrt/openwrt
          REPO_BRANCH: openwrt-21.02
        run: git clone $REPO_URL -b $REPO_BRANCH openwrt

      - name: 自定义配置
        env:
          CUSTOM_SH: 'custom.sh'
        run: |
          cd openwrt
          rm ./target/linux/ramips/image/mt7620.mk
          rm ./target/linux/ramips/dts/mt7620a_phicomm_psg1218.dtsi
          curl https://raw.githubusercontent.com/shownb/k2_openwrt_16m/main/mt7620.mk -L -o ./target/linux/ramips/image/mt7620.mk
          curl https://raw.githubusercontent.com/shownb/k2_openwrt_16m/main/mt7620a_phicomm_psg1218.dtsi -L -o ./target/linux/ramips/dts/mt7620a_phicomm_psg1218.dtsi
          mv ../21.02/$CUSTOM_SH ./ && chmod 777 $CUSTOM_SH && ./$CUSTOM_SH

      - name: 构建程序包
        run: |
          cd openwrt
          echo "here do noting"
          #echo -e "src-git routing https://git.openwrt.org/feed/routing.git" >> feeds.conf.default
          #echo -e "src-git telephony https://git.openwrt.org/feed/telephony.git" >> feeds.conf.default
          
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: config文件
        run: |
          cd openwrt
          rm -f .config*
          cp ../21.02/config.config .config
          make defconfig

      - name: 下载编译所需源码
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: 多线程编译
        run: |
          cd openwrt
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          
      - name: 单线程编译
        if: failure()
        run: |
          cd openwrt
          make -j1 V=s

      - name: 清理不必要的文件
        run: |
          cd openwrt
          find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}
          find ./bin/targets/ -name "*rootfs*img*" | xargs rm -rf {}

      - name: 上传固件
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.FIRMWARE }}
          path: ./openwrt/bin/targets/
