name: K2_8M_Spi

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: env prepare
      run: |
        sudo -E apt-get update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
    - name: run compile.sh
      run: |
        sudo chmod +x ./compile.sh
        ./compile.sh
    - name: Assemble artifact
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        find ./ -name "*sysupgrade*bin" | xargs -i mv -f {} ./artifact/
      continue-on-error: true
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt firmware
        path: ./artifact/
